/* // REGRAS: NÃO COLOQUE ACENTO NAS STRINGS \\ */
export const ENUM_USER_ROLES: string[] = [
    'PROFESSOR', 'DESENVOLVEDOR', 'USUARIO'
];

export type ENUM_USER_ROLES_TYPE = 'PROFESSOR'| 'DESENVOLVEDOR' | 'USUARIO'

export const ENUM_USER_STATUS: string[] = [
    'ACTIVE', 'INACTIVE', 'PENDING', 'BLOCKED',
]

